name: Release

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version:
        description: Select version to publish
        options:
          - patch
          - minor
          - major
        required: true
        type: choice

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Retrieve Yarn Cache Directory
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install --prefer-offline

      - name: Test Code
        run: |
          yarn test

      - name: Bump Package Version
        run: |
          yarn version --${{ github.event.inputs.version }}

      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn publish

      - name: Push Version Update & Tags
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
